name: debug_hit_points
description: "Renders a dot matrix on top of your Widget, displaying exactly where hit tests succeed"
version: 1.0.0+1
homepage: https://github.com/benthillerkus/debug_hit_points
repository: https://github.com/benthillerkus/debug_hit_points
topics: [debug, indicator, mesh, dotted, gesture]
screenshots:
  - description: 'The example app showing dots overlayed onto a rotated text and a circle drawn through a custom painter'
    path: screenshot.webp

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
